version: '3'

services:
  puppetserver:
    container_name: puppetserver
    hostname: puppet
    image:  puppet/puppetserver
    ports:
      - 8140
    volumes:
      - ./nodes/puppetserver/code:/etc/puppetlabs/code/
  puppetdb-postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    # networks:
    #   - devops-nw
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    expose:
      - 5432
  puppetdb:
    depends_on:
      - puppetdb-postgres
    hostname: puppetdb
    container_name: puppetdb
    image: puppet/puppetdb
    ports:
      - 8080:8080
      - 8081
  ubuntu1:
    hostname: ubuntu1
    container_name: ubuntu1
    ports:
      - 8085:80
    depends_on:
      - puppetserver
    image:  puppet/puppet-agent-ubuntu
    command: "agent --verbose --no-daemonize --summarize"
    